config/routes.rb
Rails.application.routes.draw do
  resources :mutants

  root 'welcome#index'

end

app/models/mutant.rb
class Mutant < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mutants_controller.rb
class MutantsController < ApplicationController
  before_action :set_mutant, only: [:show, :edit, :update, :destroy]

  # GET /mutants
  # GET /mutants.json
  def index
    @mutants = Mutant.all
  end

  # GET /mutants/1
  # GET /mutants/1.json
  def show
  end

  # GET /mutants/new
  def new
    @mutant = Mutant.new
  end

  # GET /mutants/1/edit
  def edit
  end

  # POST /mutants
  # POST /mutants.json
  def create
    @mutant = Mutant.new(mutant_params)

    respond_to do |format|
      if @mutant.save
        format.html { redirect_to @mutant, notice: 'Mutant was successfully created.' }
        format.json { render :show, status: :created, location: @mutant }
      else
        format.html { render :new }
        format.json { render json: @mutant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mutants/1
  # PATCH/PUT /mutants/1.json
  def update
    respond_to do |format|
      if @mutant.update(mutant_params)
        format.html { redirect_to @mutant, notice: 'Mutant was successfully updated.' }
        format.json { render :show, status: :ok, location: @mutant }
      else
        format.html { render :edit }
        format.json { render json: @mutant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mutants/1
  # DELETE /mutants/1.json
  def destroy
    @mutant.destroy
    respond_to do |format|
      format.html { redirect_to mutants_url, notice: 'Mutant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mutant
      @mutant = Mutant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mutant_params
      params.require(:mutant).permit(:name, :power, :age, :real_name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @mutant = Mutant.new
    @message = "Your nose has a very pleasant shape."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mutants_helper.rb
module MutantsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MutantRegistration</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mutants/_form.html.erb
<%= form_for(@mutant) do |f| %>
  <% if @mutant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mutant.errors.count, "error") %> prohibited this mutant from being saved:</h2>

      <ul>
      <% @mutant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :power %><br>
    <%= f.text_field :power %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :real_name %><br>
    <%= f.text_field :real_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mutants/edit.html.erb
<h1>Editing Mutant</h1>

<%= render 'form' %>

<%= link_to 'Show', @mutant %> |
<%= link_to 'Back', mutants_path %>

app/views/mutants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mutants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Power</th>
      <th>Age</th>
      <th>Real name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mutants.each do |mutant| %>
      <tr>
        <td><%= mutant.name %></td>
        <td><%= mutant.power %></td>
        <td><%= mutant.age %></td>
        <td><%= mutant.real_name %></td>
        <td><%= link_to 'Show', mutant %></td>
        <td><%= link_to 'Edit', edit_mutant_path(mutant) %></td>
        <td><%= link_to 'Destroy', mutant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mutant', new_mutant_path %>

app/views/mutants/new.html.erb
<h1>New Mutant</h1>

<%= render 'form' %>

<%= link_to 'Back', mutants_path %>

app/views/mutants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mutant.name %>
</p>

<p>
  <strong>Power:</strong>
  <%= @mutant.power %>
</p>

<p>
  <strong>Age:</strong>
  <%= @mutant.age %>
</p>

<p>
  <strong>Real name:</strong>
  <%= @mutant.real_name %>
</p>

<%= link_to 'Edit', edit_mutant_path(@mutant) %> |
<%= link_to 'Back', mutants_path %>

app/views/welcome/index.html.erb
<h1>Holy crap! It works!!!</h1>

<p>
  <%= @mutant.name %> says, "<%= @message %>"
</p>